from pathlib import Path
from typing import NamedTuple, Self

from pyochain import Iter


def generate_themes(caller: Path, dest: Path) -> int:
    from pygments.styles._mapping import (  # pyright: ignore[reportMissingTypeStubs]  # noqa: PLC2701
        STYLES,
    )

    content = (
        Iter(STYLES.values()).map_star(lambda _, style, __: f'"{style}"').join(" ,")
    )
    content = f"Themes = Literal[{content}]"

    doc = """Themes available for SQL syntax highlighting in the `sql_query` method."""

    return _build_content(
        dest, caller, "# theme marker START", "# theme marker END", content, doc
    )


def generate_nodes(caller: Path, dest: Path) -> int:
    from src.belugas._plan import nodes  # noqa: PLC2701

    def all_subclasses(cls: type) -> Iter[type]:
        def _subcls() -> Iter[type]:
            return Iter(cls.__subclasses__())

        return _subcls().chain(_subcls().flat_map(all_subclasses))

    content = (
        all_subclasses(nodes.BaseNode)
        .map(lambda cls: cls.__name__)
        .filter(lambda name: not name.startswith("_"))
        .unique()
        .sort()
        .join(" | ")
    )
    content = f"Node = ({content})"

    doc = """All nodes that can be part of the logical plan.

Each node represents a logical operation to be performed on the data, such as filtering, joining, or aggregating.

They just hold the input arguments for the operation, and are used to build the logical plan before it's compiled into executable code.

Note:
    - `Node` is a type alias for the union of all public `Node` subclasses.
    - `BaseNode` is the base class for all nodes, but should not be used directly.

    We do this because Python does not have built-in support for Enums with associated data like Rust does.

    Using dataclasses for each node allows us to easily store the necessary information for each operation,

    while still being able to treat them as a unified type when building the plan, relying on the type checker to ensure exhaustiveness when matching on them.
    """

    return _build_content(
        dest, caller, "# plan node marker START", "# plan node marker END", content, doc
    )


def _build_content(  # noqa: PLR0913, PLR0917
    dest: Path, caller: Path, start_marker: str, end_marker: str, content: str, doc: str
) -> int:
    warning = _warning(caller)
    file_content = dest.read_text(encoding="utf-8")
    idxs = Indexes.new(file_content, start_marker, end_marker)
    new_content = f"""
{file_content[: idxs.start + len(start_marker)]}
{content}
'''{doc}
{warning}'''
{file_content[idxs.end :]}"""
    return dest.write_text(new_content, encoding="utf-8")


class Indexes(NamedTuple):
    start: int
    end: int

    @classmethod
    def new(cls, file_content: str, start_marker: str, end_marker: str) -> Self:
        start_idx = file_content.find(start_marker)
        end_idx = file_content.find(end_marker)
        return cls(start_idx, end_idx)


def _warning(caller: Path) -> str:
    return f"""
Dynamically generated by `{caller.as_posix()}`.

Do NOT edit manually.
"""
